### PR TITLE
grid layout

### PR DESCRIPTION
**Pull request by harshalini**
Added grid component in component library
The grids are -
1) 2 column grid layout
2) 3 column grid layout
3) Responsive grid layout
Screenshot (440)
Screenshot (441)
Screenshot (442)
Check the preview here ->
https://623db6872b9c516224722321--legendary-basbousa-9c31d5.netlify.app/documentation/documentation.html#grid-div

### CODE REVIEW

**Review by dev-enforced — APPROVED** [review]
The live preview of the Grids component provide by Lini UI looks good: https://deploy-preview-19--legendary-basbousa-9c31d5.netlify.app/documentation/documentation.html#grid-div
The CSS code also looks good and easy to understand!! You can also check that this component gets displayed in the same manner as it is shown in the docs
Good work @harshalini !!

**Comment by harshalini** [comment]
> The live preview of the Grids component provide by Lini UI looks good: https://deploy-preview-19--legendary-basbousa-9c31d5.netlify.app/documentation/documentation.html#grid-div The CSS code also looks good and easy to understand!! You can also check that this component gets displayed in the same manner as it is shown in the docs Good work @harshalini !!

Thanks @dev-enforced !

**Review by sameep-s — APPROVED** [review]
Code looks fine but the white div's are bland to look maybe add some text in the such as for three column grid col-3 in each of them just a suggestion though.

**Comment by harshalini** [comment]
> Code looks fine but the white div's are bland to look maybe add some text in the such as for three column grid col-3 in each of them just a suggestion though.

Ok I will change it later

**Pull request merged**
